module.exports = [
  {name: 'REBEL'},
  {name: 'Парк им. 1 Мая'},
  {name: 'ЛУЧ368'},
  {name: 'ЛУЧ 368'},
  {name: 'Nebar'},
  {name: 'ИЦАЭ Нижнего Новгорода'},
  {name: 'СИНИЙ КОТ'},
  {name: 'Хитрый лис'},
  {name: 'Пивзавод'},
  {name: 'FRIENDS'},
  {name: 'Cartel'},
  {name: 'Oh My Craft'},
  {name: 'Oh,My Craft'},
  {name: 'Oh, My Craft'},
  {name: 'Oh. My Craft'},
  {name: 'Butch & dutch'},
  {name: 'Butch&Dutch'},
  {name: 'teatr_utug'},
  {name: 'склад'},
  {name: 'SKLADclub'},
  {name: 'ezGaming'},
  {name: 'Юпитер'},
  {name: 'Пивоман'},
  {name: 'Баклажан'},
  {name: 'Маяковка'},
  {name: 'PARLIAMENT'},
  {name: 'Башня Мага'},
  {name: 'DO YOU Lounge'},
  {name: 'Зебра'},
  {name: 'Alcatraz'},
  {name: 'Alcatarz'},
  {name: 'СИЯЙ'},
  {name: 'Центр театрального мастерства'},
  {name: 'Синий Соловей'},
  {name: 'Кинофактура'},
  {name: 'Арт-кофейня Счастье'},
  {name: 'Black cat'},
  {name: 'MORIARTY'},
  {name: 'коворкинг "Гараж"'},
  {name: 'DKRT'},
  {name: 'ПМ Бар'},
  {name: 'RETROwave'},
  {name: 'Победа'},
  {name: 'Коворкинг Сбербанка'},
  {name: 'GATSBY'},
  {name: 'Street Food Market'},
  {name: 'Матрёшка'},
  {name: 'Family Community'},
  {name: 'Горькая'},
  {name: 'Студия DOM'},
  {name: 'Точка'},
  {name: 'НОК ИПФ РАН'},
  {name: 'YogaSphera'},
  {name: 'ЭМОЦИИ'},
  {name: 'ННГУ'},
  {name: 'Три Солнца'},
  {name: 'Rock Bar'},
  {name: 'Клуб личного развития'},
  {name: 'tiu.brand'},
  {name: 'GARAGE CO-WORK'},
  {name: 'Good Foot'},
  {name: 'УТЮГ'},
  {name: 'Premio'},
  {name: 'Рекорд'},
  {name: 'Никитин'}
];
